projeto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

# recipes:recipe
app_name = 'recipes'


urlpatterns = [
    path('', views.home,name="home"),
    path('recipes/category/<int:category_id>/', views.category,name="category"),
    path('recipes/<int:id>/', views.recipe,name="recipe"),

]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    praparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True,default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True,blank=True,default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return  self.title

recipes/views.py
from django.http import Http404
from django.shortcuts import render,get_list_or_404
from utils.recipes.factory import make_recipe
# from .models import Recipe

from recipes.models import Recipe
# Create your views here.

def home(request):
    recipes = Recipe.objects.all().filter(is_published=True)
    return render(request,'recipes/pages/home.html',context={'recipes':recipes,})

def category(request, category_id):
    recipes = Recipe.objects.filter(
        category__id=category_id,
        is_published=True,
    ).order_by('-id')

    if not recipes:
        raise Http404('Not found 🥲')

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes.first().category.name} - Category | '
    })

def recipe(request, id):
    recipe = Recipe.objects.filter(
        pk=id,
        is_published=True,
    ).order_by('-id').first()

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html'%}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
       {% include "recipes/partials/recipe.html" %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}ALTERAR | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://github.com/CaioSantdev" target="_blank" rel="noreferrer noopener">By Caio Santos</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css"
        integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/brands.min.css"
        integrity="sha512-DJLNx+VLY4aEiEQFjiawXaiceujj5GA7lIY8CHCIGQCBPfsEG0nGz1edb4Jvw1LR7q031zS5PpPqFuPA8ihlRA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/solid.min.css"
        integrity="sha512-Hp+WwK4QdKZk9/W0ViDvLunYjFrGJmNDt6sCflZNkjgvNq9mY+0tMbd6tWMiAlcf1OQyqL4gn2rYp7UsfssZPA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{%static 'recipes/css/styles.css'%}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url "recipes:home" %}">
                <i class="fas fa-utensils main-logo-icon"></i>
                <span class="main-logo-text"> Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">

        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </span>
        {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at}}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}

</div>

recipes/templates/recipes/partials/recipes.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <img src="https://placehold.co/1280x720/png/269fe6" alt="Temporario">
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            Otávio Miranda
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2021 às 11:21
        </span>
        <span class="recipe-author-item">
            <a href="/recipes/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Vitae laudantium ex corrupti odit nisi, eos aliquam dicta explicabo odio? Adipisci laboriosam ad
            perspiciatis
            atque vel eius aspernatur, aliquid iure nesciunt.</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                0 Porções
            </div>
        </div>
    </div>

    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container"></div>
<div class="container">
    <form action="" class="search-form">
        <input type="search" class="search-input" name="search">
        <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
    </form>
</div>